[colors]
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[cursor]
[cursor.style]
blinking = "Always"
shape = "Beam"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 14.0

[window]
decorations = "full"
opacity = 0.9

[window.padding]
x = 10
y = 10
